### ISSUE TITLE
DSC version 1.2.0 - still problems with WMF 5.1 hanging

### ISSUE THREAD

**Issue by marcinbojko** [puppetlabs/puppetlabs-dsc#260]
As mentioned in: https://github.com/puppetlabs/puppetlabs-dsc/issues/240

I would like to reopen this issue - with:
puppetlabs-dsc (v1.2.0)
puppetlabs-powershell (v2.1.0)
tested on WIndows 10 Pro, version 1607, Powershell as enclosed:

Name                           Value
----                           -----
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

issues pointed out by @MikaelSmith are still present. So at least on Windows 10 Pro Anniversary Edition I am unable to run Powershell DSC.

```
Debug: 2016-11-19 07:43:23 +0100 C:\Windows\system32\WindowsPowershell\v1.0\powershell.exe -NoProfile -NonInteractive -NoLogo -ExecutionPolicy Bypass -Command - is running as pid: 5392
Debug: Waited 50 milliseconds...
Debug: Waited 50 milliseconds...
Debug: Waited 50 milliseconds...
Debug: Waited 50 milliseconds...
Debug: Waited 50 milliseconds...
Debug: 2016-11-19 07:43:23 +0100 STDOUT> At line:1 char:32

Debug: 2016-11-19 07:43:23 +0100 STDOUT> +         if ($runspace -eq $null)

Debug: 2016-11-19 07:43:23 +0100 STDOUT> +                                ~

Debug: 2016-11-19 07:43:23 +0100 STDOUT> Missing statement block after if ( condition ).

Debug: 2016-11-19 07:43:23 +0100 STDOUT>     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException

Debug: 2016-11-19 07:43:23 +0100 STDOUT>     + FullyQualifiedErrorId : MissingStatementBlock

Debug: 2016-11-19 07:43:23 +0100 STDOUT>

Debug: 2016-11-19 07:43:23 +0100 STDOUT>

Debug: 2016-11-19 07:43:23 +0100 STDOUT>

Debug: 2016-11-19 07:43:23 +0100 STDOUT>           $runspace = [RunspaceFactory]::CreateRunspace()

Debug: 2016-11-19 07:43:23 +0100 STDOUT>

Debug: 2016-11-19 07:43:23 +0100 STDOUT>           $runspace.Open()

Debug: 2016-11-19 07:43:23 +0100 STDOUT>

```

Tested with Windows 2016 GA - effects is the same

**Comment by jpogran** [comment]
@marcinbojko We fixed the issue with WMF 5.1 in the puppetlabs-powershell module. We haven't fixed it in the puppetlabs-dsc module. We wanted to get the fix into the 1.2.0 release, but ran out of time. We are currently working on this, you can track the progress [here](https://tickets.puppetlabs.com/browse/MODULES-3977)

**Comment by marcinbojko** [comment]
@jpogran Thanks for the update. By closing https://github.com/puppetlabs/puppetlabs-dsc/issues/240 it looked like the issue is already gone.

**Comment by kasperbrandenburg** [comment]
This is still broken, according to https://tickets.puppetlabs.com/browse/MODULES-3977 this is to be included in sprint: 	Modules 2017-01-11

**Comment by marcinbojko** [comment]
When using Windows Server 2016 with latest (december) updates and Powershell Version :
PS C:\Windows\system32> $PSVersionTable.PSVersion
Major Minor Build Revision
----- ----- ----- --------
5 1 14393 693
I was able to run various dsc modules (which previously hanged) like: xFirewall,xArchive and so on. All test passed, rules were created.

**Comment by kasperbrandenburg** [comment]
Did you try IIS and SQL modules? Thats what i've been testing on,and they still suffer from the endless loop

**Comment by marcinbojko** [comment]
Yes, I use xSQL and it works perfectly.


W 22 stycznia 2017 1:44:13 PM Kasper Brandenburg <notifications@github.com> 
napisał:

**Comment by jpogran** [comment]
We apologize for the delay in MODULES-3977. I'll bring this up in our next meeting and get this prioritized.

**Comment by marcinbojko** [comment]
@jpogran - please notice that situation is back to normal with latest powershell release for W2k16.

**Comment by ferventcoder** [comment]
Glad to know that there is a PowerShell version that fixes the hanging @marcinbojko !

**Comment by marcinbojko** [comment]
@ferventcoder you don't even know how I waited for this. Whole deployment of W2k16 was on hold ;)

**Comment by jpogran** [comment]
Hi,

Puppet will be shutting down the github issues tab in this repository as there already is a publicly accessible [issue tracker](https://tickets.puppetlabs.com/browse/MODULES) on March 24th, 20017.

If you want to continue the discussion from this issue, please follow the ticket already created from this issue (typically MODULES-XXXX) in our issue tracker.

If you would like to file a new issue, please follow the [template here](https://tickets.puppetlabs.com/CreateIssue.jspa?pid=10707) to create a new ticket.

Thanks,

James Pogran

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.\n\nWe're going to close it but please do raise another issue if the issue still persists. 😄
